id = "ahk2"
name = "AutoHotkey 2.0"
version = "0.0.1"
schema_version = 1
authors = ["BlessEphraem <ephraem.contact@gmail.com>"]
description = "AutoHotkey v2 syntax highlighting for Zed"
repository = "https://github.com/BlessEphraem/zed-ahk2"

[grammars.ahk2]
repository = "https://github.com/BlessEphraem/zed-ahk2"
rev = "87b305fb9bff4c199ceb5c941c4281fa35d513e6"
